export const validEnv: Record<string, string> = {
  NODE_ENV: 'test',
  BACKEND_PORT: '3000',
  MONGODB_URI: 'mongodb://localhost:27017/helpeme-test',
  JWT_SECRET: 'test-secret-with-enough-length-123',
  JWT_EXPIRES_IN: '1h',
  COOKIE_SECURE: 'false',
  CORS_ORIGIN: 'http://localhost:8080',
  BCRYPT_ROUNDS: '4',
  UPLOAD_DIR: '/tmp/helpeme-uploads',
  MAX_UPLOAD_SIZE_MB: '5',
  MAX_FILES_PER_REQUEST: '5',
  RUN_SEED: 'false',
  ADMIN_ROOT_NAME: 'Admin Root',
  ADMIN_ROOT_EMAIL: 'admin@example.com',
  ADMIN_ROOT_PASSWORD: 'Test123@',
  LOG_LEVEL: 'silent',
  PAGINATION_MAX_LIMIT: '50',
  THROTTLE_TTL: '60',
  THROTTLE_LIMIT: '10',
};
